"""post table

Revision ID: 7f336703c45a
Revises: cf960ddafc53
Create Date: 2018-06-21 10:52:59.085875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f336703c45a'
down_revision = 'cf960ddafc53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_UserTable_email'), 'UserTable', ['email'], unique=True)
    op.create_index(op.f('ix_UserTable_username'), 'UserTable', ['username'], unique=True)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['UserTable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.drop_index('ix_TestTable_email', table_name='TestTable')
    op.drop_index('ix_TestTable_username', table_name='TestTable')
    op.drop_table('TestTable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TestTable',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_TestTable_username', 'TestTable', ['username'], unique=1)
    op.create_index('ix_TestTable_email', 'TestTable', ['email'], unique=1)
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_UserTable_username'), table_name='UserTable')
    op.drop_index(op.f('ix_UserTable_email'), table_name='UserTable')
    op.drop_table('UserTable')
    # ### end Alembic commands ###
